version: '3.8'

networks:
  laravel:

volumes: 
  practice-volume:

services:
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    command: "--log-bin-trust-function-creators=1 --default-authentication-plugin=mysql_native_password"
    volumes:
      - practice-volume:/var/lib/mysql
    networks:
      - laravel
    cap_add:
      - SYS_NICE  

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: app
    container_name: app
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose: 
      - 9000
    networks:
      - laravel